frontend:
  - changed-files:
      - any-glob-to-any-file:
          - frontend/**

CI:
  - changed-files:
      - any-glob-to-any-file:
          - .github/**

feature:
  - head-branch:
      - "^feature/"
